/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/q78qlbK
 */
import {
  AccordionTrigger,
  AccordionContent,
  AccordionItem,
  Accordion,
} from "@/components/ui/accordion";
import { CardContent, Card } from "@/components/ui/card";

const qaArray = [
  {
    question: "What are GPTs in the context of the GPTs Store?",
    answer:
      "GPTs are custom versions of ChatGPT tailored for specific purposes, enhancing daily life, work, or entertainment, and can be shared with others. They are integrated into the GPTs Store for easy access and use.",
  },
  {
    question: "Is coding knowledge required to build GPTs for the GPTs Store?",
    answer:
      "No coding knowledge is required to build GPTs. The process is designed to be as simple as starting a conversation, making it accessible for everyone to create and share through the GPTs Store.",
  },
  {
    question: "Can I try example GPTs through the GPTs Store?",
    answer:
      "Yes, example GPTs like Canva and Zapier AI Actions are available for ChatGPT Plus and Enterprise users to try, with plans to offer more through the GPTs Store soon.",
  },
  {
    question: "How can I monetize my GPTs in the GPTs Store?",
    answer:
      "Creators can earn money through the GPTs Store based on the usage of their GPTs, with detailed monetization plans to be rolled out in the coming months.",
  },
  {
    question:
      "How does the GPTs Store ensure the privacy and safety of my data?",
    answer:
      "The GPTs Store has privacy controls allowing users to manage their data, opt out of model training, and decide if their interactions can be used for model improvement.",
  },
  {
    question:
      "Are there any safeguards against harmful GPTs in the GPTs Store?",
    answer:
      "The GPTs Store has systems to review GPTs against usage policies, aiming to prevent the sharing of harmful content and building user trust through identity verification.",
  },
  {
    question:
      "What future developments are expected for GPTs in the GPTs Store?",
    answer:
      "GPTs are expected to become smarter and more capable, eventually undertaking real-world tasks as 'agents', with a careful approach to technical and safety work.",
  },
  {
    question: "Can developers connect GPTs to real-world data and services?",
    answer:
      "Developers can define custom actions for GPTs, allowing integration with external data and services, such as databases, emails, or e-commerce platforms, through the GPTs Store.",
  },
];

export function FAQ() {
  return (
    <div className="flex items-center justify-center ">
      <Card className="w-[650px] shadow-lg">
        <CardContent className="p-6">
          <h2 className="text-2xl font-semibold">Frequently Asked Questions</h2>
          <Accordion className="mt-4 w-full" collapsible="" type="multiple">
            {qaArray.map((item, idx) => {
              const v = `item-${idx}`;
              if (idx !== qaArray.length - 1) {
                return (
                  <AccordionItem value={v} key={idx}>
                    <AccordionTrigger className="hover:underline-none">
                      {item.question}
                    </AccordionTrigger>
                    <AccordionContent>{item.answer}</AccordionContent>
                  </AccordionItem>
                );
              } else {
                return (
                  <AccordionItem key={idx} className="border-b-0" value={v}>
                    <AccordionTrigger className="hover:underline-none">
                      {item.question}
                    </AccordionTrigger>
                    <AccordionContent>{item.answer}</AccordionContent>
                  </AccordionItem>
                );
              }
            })}
          </Accordion>
        </CardContent>
      </Card>
    </div>
  );
}
